wip comparison testing

diff --git a/.github/workflows/integration-testing.yaml b/.github/workflows/integration-testing.yaml
--- a/.github/workflows/integration-testing.yaml
+++ b/.github/workflows/integration-testing.yaml
@@ -123,6 +123,15 @@ jobs:
         with:
             oc-container-version: "${{ needs.wait_for_image_ready.outputs.IMAGE_TAG }}"
             namespace: "${{ needs.wait_for_image_ready.outputs.NAMESPACE }}"
+    build-test-stack-promless:
+        needs: wait_for_image_ready
+        if: ${{ (always() && !cancelled()) && ( github.event.event_name == 'schedule'  || github.event_name == 'push' || github.event_name == 'merge_group' || (github.event_name == 'pull_request_target'  && needs.check_actor_permissions.outputs.ismaintainer == 'true')) }}
+        uses: opencost/opencost-infra/.github/workflows/build-stack.yaml@main
+        secrets: inherit
+        with:
+            oc-container-version: "${{ needs.wait_for_image_ready.outputs.IMAGE_TAG }}"
+            namespace: "${{ needs.wait_for_image_ready.outputs.NAMESPACE }}-promless"
+            prometheus: false
 
     wait-for-dns:
         needs: [wait_for_image_ready, build-test-stack]
@@ -156,18 +165,50 @@ jobs:
         with:
             namespace: "${{ needs.wait_for_image_ready.outputs.NAMESPACE }}"
             target_branch: "${{ github.event.pull_request.head.ref || 'main' }}"
+  
+    wait-for-data-collection:
+      needs: [wait_for_image_ready, build-test-stack, build-test-stack-promless]
+      runs-on: ubuntu-latest
+      if: ${{ (always() && !cancelled()) && ( github.event.event_name == 'schedule'  || github.event_name == 'push' || github.event_name == 'merge_group' || (github.event_name == 'pull_request_target'  && needs.check_actor_permissions.outputs.ismaintainer == 'true')) }}
+      permissions: {}
+      steps:
+        - name: Wait 15 minutes for promless data collection
+          run: |
+            sleep 15m
     
+    run-comparison-tests:
+      needs: [wait_for_image_ready, build-test-stack, build-test-stack-promless, wait-for-data-collection]
+      runs-on: ubuntu-latest
+      if: ${{ (always() && !cancelled()) && ( github.event.event_name == 'schedule'  || github.event_name == 'push' || github.event_name == 'merge_group' || (github.event_name == 'pull_request_target'  && needs.check_actor_permissions.outputs.ismaintainer == 'true')) }}
+      permissions: {}
+      uses: opencost/opencost-infra/.github/workflows/test-stack.yaml@main
+      secrets: inherit
+      with:
+        namespace: "${{ needs.wait_for_image_ready.outputs.NAMESPACE }}"
+        comparison_namespace: "${{ needs.wait_for_image_ready.outputs.NAMESPACE }}-promless"
+        target_branch: "${{ github.event.pull_request.head.ref || 'main' }}"
+        comparison: true
+           
     teardown-test-stack:
-        needs: [wait_for_image_ready, run-tests]
+        needs: [wait_for_image_ready, run-tests, run-comparison-tests]
         if: ${{ (always() && !cancelled()) && ( github.event.event_name == 'schedule'  || github.event_name == 'push' || github.event_name == 'merge_group' || (github.event_name == 'pull_request_target'  && needs.check_actor_permissions.outputs.ismaintainer == 'true')) }}
         uses: opencost/opencost-infra/.github/workflows/destroy-stack.yaml@main
         secrets: inherit 
         permissions: {}
         with:
             namespace: "${{ needs.wait_for_image_ready.outputs.NAMESPACE }}"
+    
+    teardown-test-stack-comparison:
+        needs: [wait_for_image_ready, run-comparison-tests]
+        if: ${{ (always() && !cancelled()) && ( github.event.event_name == 'schedule'  || github.event_name == 'push' || github.event_name == 'merge_group' || (github.event_name == 'pull_request_target'  && needs.check_actor_permissions.outputs.ismaintainer == 'true')) }}
+        uses: opencost/opencost-infra/.github/workflows/destroy-stack.yaml@main
+        secrets: inherit 
+        permissions: {}
+        with:
+            namespace: "${{ needs.wait_for_image_ready.outputs.NAMESPACE }}-promless"
 
     check-success:
-        needs: [noop-tests, run-tests]
+        needs: [noop-tests, run-tests, run-comparison-tests]
         permissions: {}
         runs-on: ubuntu-latest
         if: ${{ always() }}
@@ -184,11 +225,16 @@ jobs:
                 exit 1
               fi
               
+              if [[ "${{ needs.run-comparison-tests.outputs.passed }}" != "true" ]]; then
+                echo "One or more comparison tests failed"
+                exit 1
+              fi
+              
               echo "All integration tests passed"
               exit 0
 
     set-labels:
-      needs: [wait_for_image_ready, run-tests]
+      needs: [noop-tests, run-tests, run-comparison-tests]
       if: ${{ (always() && !cancelled()) && ( github.event_name == 'pull_request_target' && needs.check_actor_permissions.outputs.ismaintainer == 'true') }}
       runs-on: ubuntu-latest
       permissions: {}
